### ISSUE TITLE
odd error

### ISSUE THREAD

**Issue by h-parks** [fleXible/ha-onkyo-custom#1]
I like this idea but I can't seem to make it work in 0.112.4. I would love to see the unnecessary zones disappear.

After adding the `onkyo_custom` folder to `custom_components` and restarting, I receive the error: 

`Platform error media_player.onkyo_custom - No module named 'custom_components.onkyo'`

**Comment by fleXible** [comment]
That is particularly odd, as there is no reference in the code to a module `custom_components.onkyo`.
Did you change anything in your your config file? If so, please paste the part here and try restarting without it, so I may get an idea from where this may come from.

**Comment by fishredleung** [comment]
```
Integration error: onkyo_custom - Integration 'onkyo_custom' not found.
Platform error media_player.onkyo_custom - Integration 'onkyo_custom' not found.
```
no it doesnt work

**Comment by fleXible** [comment]
Hi @fishredleung,
could you post the relevant parts of your config here? I checked with the code and found this exact error message is only produced when home assistant checks the config. I guess, you have something along the lines like this:
````yaml
media_player:
  - platform: onkyo_custom
    host: 192.168.1.2
    name: receiver
````
If so, just check my first comment for a working example config.

**Comment by fishredleung** [comment]
Hi, thanks for your quick response, here is my config:
`onkyo_custom:

media_player:
  - platform: onkyo_custom
    host: 192.168.50.216
    name: Onkyo
    sources:
     bd-dvd: "Karoake"
     strm-box: "Google TV"`

Actually I just copied your example , but just changed the ip address of my AVR

**Comment by fishredleung** [comment]
Thank you for your quick response, changed my config, works now. But restart function of HA didnt work because it cannot recognize the custom component file
`onkyo_custom:

media_player:
  - platform: onkyo
    host: 192.168.50.216
    name: Onkyo
    sources:
     bd-dvd: "Karoake"
     strm-box: "Google TV"
`

**Comment by fleXible** [comment]
The safest approach with custom_components is to install with HACS including a restart first and change the config in a second step. Home Assistant happily loads everything in `custom_components` even without config.
